{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 6,
  "build_id": "v0.99.1",
  "game_mode": "daily",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.DECAY"
              },
              {
                "id": "CARD.SECRET_WEAPON"
              },
              {
                "id": "CARD.PANACHE"
              },
              {
                "id": "CARD.MASTER_OF_STRATEGY"
              },
              {
                "id": "CARD.PANIC_BUTTON"
              },
              {
                "id": "CARD.SECRET_TECHNIQUE"
              },
              {
                "id": "CARD.BULLET_TIME"
              },
              {
                "id": "CARD.OUTBREAK"
              },
              {
                "id": "CARD.NOXIOUS_FUMES"
              },
              {
                "id": "CARD.DEADLY_POISON"
              },
              {
                "id": "CARD.DEFLECT"
              },
              {
                "id": "CARD.BACKFLIP"
              },
              {
                "id": "CARD.CLOAK_AND_DAGGER"
              },
              {
                "id": "CARD.DAGGER_THROW"
              },
              {
                "id": "CARD.BACKSTAB"
              },
              {
                "id": "CARD.SLICE"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ALL_STAR.title",
                  "table": "modifiers"
                }
              },
              {
                "title": {
                  "key": "SEALED_DECK.title",
                  "table": "modifiers"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655
          },
          {
            "cards_gained": [
              {
                "id": "CARD.DECAY"
              },
              {
                "id": "CARD.THE_BOMB"
              },
              {
                "id": "CARD.MASTER_OF_STRATEGY"
              },
              {
                "id": "CARD.DRAMATIC_ENTRANCE"
              },
              {
                "id": "CARD.COORDINATE"
              },
              {
                "id": "CARD.HUDDLE_UP"
              },
              {
                "id": "CARD.SHRUG_IT_OFF"
              },
              {
                "id": "CARD.ARMAMENTS"
              },
              {
                "id": "CARD.BODY_SLAM"
              },
              {
                "id": "CARD.INFERNAL_BLADE"
              },
              {
                "id": "CARD.TAUNT"
              },
              {
                "id": "CARD.STOMP"
              },
              {
                "id": "CARD.PILLAGE"
              },
              {
                "id": "CARD.POMMEL_STRIKE"
              },
              {
                "id": "CARD.SETUP_STRIKE"
              },
              {
                "id": "CARD.IRON_WAVE"
              }
            ],
            "current_gold": 99,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ALL_STAR.title",
                  "table": "modifiers"
                }
              },
              {
                "title": {
                  "key": "SEALED_DECK.title",
                  "table": "modifiers"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ESCAPE_PLAN"
              }
            ],
            "current_gold": 109,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.TWIN_STRIKE"
              }
            ],
            "current_gold": 110,
            "current_hp": 68,
            "damage_taken": 2,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.BULLET_TIME"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BULLET_TIME"
              }
            ],
            "current_gold": 123,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.ANGER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FIGHT_ME"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 3,
                "id": "CARD.ANGER"
              }
            ],
            "current_gold": 121,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BACKFLIP"
              }
            ],
            "current_gold": 133,
            "current_hp": 52,
            "damage_taken": 4,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.ATTACK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.WHIRLWIND"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 4,
                "id": "CARD.WHIRLWIND"
              }
            ],
            "current_gold": 133,
            "current_hp": 77,
            "damage_taken": 3,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 133,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DOORS_OF_LIGHT_AND_DARK.pages.INITIAL.options.DARK.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655
          },
          {
            "current_gold": 133,
            "current_hp": 77,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DOORS_OF_LIGHT_AND_DARK.pages.INITIAL.options.LIGHT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "upgraded_cards": [
              "CARD.SHRUG_IT_OFF",
              "CARD.SETUP_STRIKE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DOORS_OF_LIGHT_AND_DARK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 133,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BULLET_TIME"
            ]
          },
          {
            "current_gold": 133,
            "current_hp": 77,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.WHIRLWIND"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.LEG_SWEEP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 146,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 7,
                "id": "CARD.MOLTEN_FIST"
              }
            ],
            "current_gold": 148,
            "current_hp": 79,
            "damage_taken": 4,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAND_FINALE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.VOLLEY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_OF_GREED"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 3,
                "id": "CARD.BULLET_TIME"
              }
            ],
            "current_gold": 71,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.POISON_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": false
              },
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ]
          },
          {
            "current_gold": 148,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 104,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 180,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 104,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 180,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.INFERNAL_BLADE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.ENVENOM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ENVENOM"
              }
            ],
            "current_gold": 137,
            "current_hp": 59,
            "damage_taken": 11,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.POCKETWATCH",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.EXPECT_A_FIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRIMSON_MANTLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.EXPECT_A_FIGHT"
              }
            ],
            "current_gold": 212,
            "current_hp": 76,
            "damage_taken": 9,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_used": [
              "POTION.HEART_OF_IRON"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GIRYA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 137,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ENVENOM"
            ]
          },
          {
            "current_gold": 212,
            "current_hp": 76,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "LIFT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STRANGLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FOOTWORK"
              }
            ],
            "current_gold": 170,
            "current_hp": 52,
            "damage_taken": 9,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.HEADBUTT"
              }
            ],
            "current_gold": 240,
            "current_hp": 69,
            "damage_taken": 13,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.OROBIC_ACID",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STURDY_CLAMP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PINPOINT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DAGGER_SPRAY"
              }
            ],
            "current_gold": 180,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.POWDERED_DEMISE"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.HEADBUTT"
              }
            ],
            "current_gold": 254,
            "current_hp": 64,
            "damage_taken": 11,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 20,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GREMLIN_MERC_NORMAL",
            "monster_ids": [
              "MONSTER.GREMLIN_MERC"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 180,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 16,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 254,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "LIFT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.KNIFE_TRAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NIGHTMARE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ABRASIVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DOUBT"
              }
            ],
            "current_gold": 255,
            "current_hp": 54,
            "damage_taken": 16,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.CRUELTY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THRASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CASCADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.CRUELTY"
              },
              {
                "id": "CARD.NORMALITY"
              }
            ],
            "current_gold": 329,
            "current_hp": 31,
            "damage_taken": 39,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.SHIP_IN_A_BOTTLE",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.WATERFALL_GIANT_BOSS",
            "monster_ids": [
              "MONSTER.WATERFALL_GIANT"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SEAL_OF_GOLD",
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PUMPKIN_CANDLE",
                "title": {
                  "key": "PUMPKIN_CANDLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 255,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 12,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.SEAL_OF_GOLD",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SEAL_OF_GOLD",
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 329,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 39,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.NUTRITIOUS_SOUP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CLOAK_AND_DAGGER"
              }
            ],
            "current_gold": 255,
            "current_hp": 68,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 15,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.SKILL_POTION",
              "POTION.GAMBLERS_BREW"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.INFLAME"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HEMOKINESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.INFLAME"
              }
            ],
            "current_gold": 342,
            "current_hp": 70,
            "damage_taken": 6,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 255,
            "current_hp": 63,
            "damage_taken": 5,
            "event_choices": [
              {
                "title": {
                  "key": "DOLL_ROOM.pages.INITIAL.options.TAKE_SOME_TIME.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "DAUGHTER_OF_THE_WIND.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.DAUGHTER_OF_THE_WIND",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 342,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DOLL_ROOM.pages.INITIAL.options.RANDOM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.BING_BONG",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DOLL_ROOM",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 155,
            "current_hp": 63,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WELCOME_TO_WONGOS.pages.INITIAL.options.BARGAIN_BIN.title",
                  "table": "events"
                },
                "variables": {
                  "BargainBinCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 100,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 300,
                    "bool_value": false,
                    "string_value": null
                  },
                  "FeaturedItemCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 200,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxRelicCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxCombatCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 5,
                    "bool_value": false,
                    "string_value": null
                  },
                  "WongoPointAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 64,
                    "bool_value": false,
                    "string_value": null
                  },
                  "RemainingWongoPointAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 1936,
                    "bool_value": false,
                    "string_value": null
                  },
                  "TotalWongoBadgeAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "RandomRelic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Kunai"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 42,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WELCOME_TO_WONGOS.pages.INITIAL.options.MYSTERY_BOX.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 300,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.WONGOS_MYSTERY_TICKET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WELCOME_TO_WONGOS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.DODGE_AND_ROLL"
              },
              {
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 155,
            "current_hp": 63,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655
          },
          {
            "cards_gained": [
              {
                "id": "CARD.POMMEL_STRIKE"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.POMMEL_STRIKE"
              },
              {
                "id": "CARD.SWORD_BOOMERANG"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.SWORD_BOOMERANG"
              }
            ],
            "current_gold": 42,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 155,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BACKFLIP"
            ]
          },
          {
            "current_gold": 42,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "LIFT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FISTICUFFS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DAGGER_THROW"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.DOUBT"
              }
            ],
            "current_gold": 30,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.POISON_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": false
              },
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": false
              },
              {
                "choice": "RELIC.WING_CHARM",
                "was_picked": false
              }
            ]
          },
          {
            "current_gold": 42,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 66,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 78,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.WHETSTONE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.PILLAGE",
              "CARD.TWIN_STRIKE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 66,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BACKFLIP"
            ]
          },
          {
            "current_gold": 78,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.CRUELTY"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": false
              }
            ],
            "current_gold": 76,
            "current_hp": 50,
            "damage_taken": 15,
            "gold_gained": 30,
            "gold_lost": 20,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.UPPERCUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 26,
                "id": "CARD.UPPERCUT"
              },
              {
                "floor_added_to_deck": 26,
                "id": "CARD.UPPERCUT"
              }
            ],
            "current_gold": 111,
            "current_hp": 38,
            "damage_taken": 38,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KUNAI",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.ENTOMANCER_ELITE",
            "monster_ids": [
              "MONSTER.ENTOMANCER"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 76,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 111,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.EXPECT_A_FIGHT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.AFTERIMAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.AFTERIMAGE"
              }
            ],
            "current_gold": 94,
            "current_hp": 63,
            "damage_taken": 7,
            "gold_gained": 33,
            "gold_lost": 15,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 28,
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 28,
                "id": "CARD.BODY_SLAM"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 28,
                "id": "CARD.BODY_SLAM"
              }
            ],
            "current_gold": 137,
            "current_hp": 14,
            "damage_taken": 30,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.OROBIC_ACID"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 94,
            "current_hp": 63,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.GRAB_POTIONS.title",
                  "table": "events"
                },
                "variables": {
                  "FoulPotions": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 137,
            "current_hp": 14,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.RANSACK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.POTION_COURIER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 94,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.AFTERIMAGE"
            ]
          },
          {
            "current_gold": 137,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 39,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.ADRENALINE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TRACKING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BURST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ADRENALINE"
              },
              {
                "id": "CARD.REGRET"
              }
            ],
            "current_gold": 129,
            "current_hp": 50,
            "damage_taken": 15,
            "gold_gained": 75,
            "gold_lost": 40,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.BARRICADE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DARK_EMBRACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEMON_FORM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.BARRICADE"
              },
              {
                "floor_added_to_deck": 31,
                "id": "CARD.BARRICADE"
              },
              {
                "id": "CARD.GUILTY",
                "props": {
                  "ints": [
                    {
                      "name": "CombatsSeen",
                      "value": 0
                    }
                  ]
                }
              },
              {
                "floor_added_to_deck": 31,
                "id": "CARD.GUILTY",
                "props": {
                  "ints": [
                    {
                      "name": "CombatsSeen",
                      "value": 0
                    }
                  ]
                }
              }
            ],
            "current_gold": 212,
            "current_hp": 7,
            "damage_taken": 41,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_used": [
              "POTION.WEAK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SPIKED_GAUNTLETS",
                "title": {
                  "key": "SPIKED_GAUNTLETS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CLAWS",
                "title": {
                  "key": "CLAWS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "MEAT_CLEAVER",
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 129,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 16,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.MEAT_CLEAVER",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "MEAT_CLEAVER",
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CLAWS",
                "title": {
                  "key": "CLAWS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 212,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 58,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.SAI",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 134,
            "current_hp": 65,
            "damage_taken": 3,
            "gold_gained": 15,
            "gold_lost": 10,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.SWIFT_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 33,
                  "id": "CARD.INFERNAL_BLADE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 33,
                "id": "CARD.INFERNAL_BLADE"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 33,
                "id": "CARD.INFERNAL_BLADE"
              }
            ],
            "current_gold": 221,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.BELIEVE_IN_YOU"
            ],
            "bought_potions": [
              "POTION.VULNERABLE_POTION",
              "POTION.SKILL_POTION",
              "POTION.EXPLOSIVE_AMPOULE"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FOLLOW_THROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NIGHTMARE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BELIEVE_IN_YOU"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.REGRET"
              }
            ],
            "current_gold": 74,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 300,
            "gold_lost": 0,
            "gold_spent": 360,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FOUL_POTION",
              "POTION.FOUL_POTION",
              "POTION.FOUL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": false
              },
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": false
              },
              {
                "choice": "RELIC.BREAD",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.BELIEVE_IN_YOU"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 34,
                "id": "CARD.BELIEVE_IN_YOU"
              },
              {
                "floor_added_to_deck": 34,
                "id": "CARD.BELIEVE_IN_YOU"
              },
              {
                "floor_added_to_deck": 34,
                "id": "CARD.SETUP_STRIKE"
              },
              {
                "floor_added_to_deck": 34,
                "id": "CARD.SETUP_STRIKE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.NORMALITY"
              }
            ],
            "current_gold": 5,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 141,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 65,
            "current_hp": 65,
            "damage_taken": 2,
            "gold_gained": 11,
            "gold_lost": 20,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.SKILL_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 35,
                  "id": "CARD.MANGLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SECOND_WIND"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 35,
                "id": "CARD.MANGLE"
              },
              {
                "floor_added_to_deck": 35,
                "id": "CARD.MANGLE"
              }
            ],
            "current_gold": 18,
            "current_hp": 77,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.OROBIC_ACID",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": true
              },
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              },
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 65,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GRAVE_OF_THE_FORGOTTEN.pages.INITIAL.options.ACCEPT.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Forgotten Soul"
                  },
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Soul's Power"
                  },
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Decay"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.FORGOTTEN_SOUL",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 18,
            "current_hp": 77,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GRAVE_OF_THE_FORGOTTEN.pages.INITIAL.options.ACCEPT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.FORGOTTEN_SOUL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.GRAVE_OF_THE_FORGOTTEN",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PANIC_BUTTON"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.SECRET_WEAPON"
              }
            ],
            "current_gold": 65,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 79,
            "max_hp_gained": 9,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "COOK"
            ]
          },
          {
            "current_gold": 18,
            "current_hp": 77,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.MANGLE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 98,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CALENDAR",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 55,
            "current_hp": 77,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.CLOAK_CLASP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPOSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNIFE_TRAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_BOMB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ENTROPY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SPEEDSTER"
              }
            ],
            "current_gold": 19,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 79,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.NUNCHAKU",
                "was_picked": false
              },
              {
                "choice": "RELIC.VAMBRACE",
                "was_picked": false
              },
              {
                "choice": "RELIC.NINJA_SCROLL",
                "was_picked": false
              }
            ]
          },
          {
            "current_gold": 55,
            "current_hp": 77,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 40,
                  "id": "CARD.BLUR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLUR"
              }
            ],
            "current_gold": 13,
            "current_hp": 65,
            "damage_taken": 11,
            "gold_gained": 9,
            "gold_lost": 15,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 40,
                  "id": "CARD.DEMONIC_SHIELD"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BURNING_PACT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 40,
                "id": "CARD.DEMONIC_SHIELD"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 40,
                "id": "CARD.DEMONIC_SHIELD"
              }
            ],
            "current_gold": 66,
            "current_hp": 70,
            "damage_taken": 13,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMED_BERSERKER_NORMAL",
            "monster_ids": [
              "MONSTER.SLIMED_BERSERKER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 13,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ADRENALINE"
            ]
          },
          {
            "current_gold": 66,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.MANGLE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.OUTBREAK"
              }
            ],
            "current_gold": 17,
            "current_hp": 67,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 10,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.DROPLET_OF_PRECOGNITION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.VULNERABLE_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.JUGGERNAUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 42,
                "id": "CARD.JUGGERNAUT"
              },
              {
                "floor_added_to_deck": 42,
                "id": "CARD.JUGGERNAUT"
              }
            ],
            "current_gold": 77,
            "current_hp": 73,
            "damage_taken": 3,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FROG_KNIGHT_NORMAL",
            "monster_ids": [
              "MONSTER.FROG_KNIGHT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              }
            ],
            "current_gold": 31,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 29,
            "gold_lost": 15,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.DROPLET_OF_PRECOGNITION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 43,
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 43,
                "id": "CARD.BLOODLETTING"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 43,
                "id": "CARD.BLOODLETTING"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.GUILTY",
                "props": {
                  "ints": [
                    {
                      "name": "CombatsSeen",
                      "value": 5
                    }
                  ]
                }
              },
              {
                "floor_added_to_deck": 31,
                "id": "CARD.GUILTY",
                "props": {
                  "ints": [
                    {
                      "name": "CombatsSeen",
                      "value": 5
                    }
                  ]
                }
              }
            ],
            "current_gold": 103,
            "current_hp": 46,
            "damage_taken": 33,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.OROBIC_ACID"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 31,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 103,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 34,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 1,
            "current_hp": 73,
            "damage_taken": 6,
            "gold_gained": 0,
            "gold_lost": 30,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE"
            ]
          },
          {
            "current_gold": 103,
            "current_hp": 9,
            "damage_taken": 77,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_used": [
              "POTION.VULNERABLE_POTION",
              "POTION.SPEED_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DOORMAKER_BOSS",
            "monster_ids": [
              "MONSTER.DOOR"
            ],
            "room_type": "boss",
            "turns_taken": 14
          }
        ]
      }
    ]
  ],
  "modifiers": [
    {
      "id": "MODIFIER.ALL_STAR"
    },
    {
      "id": "MODIFIER.SEALED_DECK"
    },
    {
      "id": "MODIFIER.CURSED_RUN"
    }
  ],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PANACHE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.MASTER_OF_STRATEGY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SECRET_TECHNIQUE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.BULLET_TIME"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.OUTBREAK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEADLY_POISON"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFLECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.BACKFLIP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.CLOAK_AND_DAGGER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BACKSTAB"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SLICE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.ESCAPE_PLAN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.BACKFLIP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.ENVENOM"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.DAGGER_SPRAY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.CLOAK_AND_DAGGER"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.DODGE_AND_ROLL"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.ACROBATICS"
        },
        {
          "floor_added_to_deck": 23,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.AFTERIMAGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.ADRENALINE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.BELIEVE_IN_YOU"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.SPEEDSTER"
        },
        {
          "floor_added_to_deck": 40,
          "id": "CARD.BLUR"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.OUTBREAK"
        }
      ],
      "id": 76561198854416655,
      "max_potion_slot_count": 4,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BLOOD_VIAL"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.POCKETWATCH"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.JUZU_BRACELET"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.SEAL_OF_GOLD"
        },
        {
          "floor_added_to_deck": 19,
          "id": "RELIC.DAUGHTER_OF_THE_WIND"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.ORNAMENTAL_FAN"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.MEAT_CLEAVER"
        },
        {
          "floor_added_to_deck": 36,
          "id": "RELIC.FORGOTTEN_SOUL"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.STONE_CALENDAR"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.GORGET"
        }
      ]
    },
    {
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DECAY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.THE_BOMB"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.MASTER_OF_STRATEGY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DRAMATIC_ENTRANCE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.COORDINATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.HUDDLE_UP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ARMAMENTS"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BODY_SLAM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.INFERNAL_BLADE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TAUNT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STOMP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.PILLAGE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.SETUP_STRIKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.IRON_WAVE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.TWIN_STRIKE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.ANGER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.WHIRLWIND"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.MOLTEN_FIST"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.EXPECT_A_FIGHT"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.HEADBUTT"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.HEADBUTT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.CRUELTY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.INFLAME"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.SWORD_BOOMERANG"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.SWORD_BOOMERANG"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.UPPERCUT"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.UPPERCUT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.BODY_SLAM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.BODY_SLAM"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.BARRICADE"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.BARRICADE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.INFERNAL_BLADE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.INFERNAL_BLADE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.BELIEVE_IN_YOU"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.BELIEVE_IN_YOU"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.SETUP_STRIKE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.SETUP_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 35,
          "id": "CARD.MANGLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 35,
          "id": "CARD.MANGLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 40,
          "id": "CARD.DEMONIC_SHIELD"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 40,
          "id": "CARD.DEMONIC_SHIELD"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.JUGGERNAUT"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.JUGGERNAUT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 43,
          "id": "CARD.BLOODLETTING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 43,
          "id": "CARD.BLOODLETTING"
        }
      ],
      "id": 76561198419322369,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.REGAL_PILLOW"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.GIRYA",
          "props": {
            "ints": [
              {
                "name": "TimesLifted",
                "value": 3
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.STURDY_CLAMP"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.NUTRITIOUS_SOUP"
        },
        {
          "floor_added_to_deck": 19,
          "id": "RELIC.BING_BONG"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.WONGOS_MYSTERY_TICKET",
          "props": {
            "bools": [
              {
                "name": "GaveRelic",
                "value": true
              }
            ],
            "ints": [
              {
                "name": "CombatsFinished",
                "value": 9
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.WHETSTONE"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.KUNAI"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.SAI"
        },
        {
          "floor_added_to_deck": 35,
          "id": "RELIC.ORNAMENTAL_FAN"
        },
        {
          "floor_added_to_deck": 35,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 35,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        },
        {
          "floor_added_to_deck": 36,
          "id": "RELIC.FORGOTTEN_SOUL"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.CLOAK_CLASP"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.TUNING_FORK",
          "props": {
            "ints": [
              {
                "name": "SkillsPlayed",
                "value": 7
              }
            ]
          }
        }
      ]
    }
  ],
  "run_time": 4409,
  "schema_version": 8,
  "seed": "14_04_2026_2P",
  "start_time": 1776128541,
  "was_abandoned": false,
  "win": true
}