{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 0,
  "build_id": "v0.103.2",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.BYRDONIS_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SMALL_CAPSULE",
                "title": {
                  "key": "SMALL_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 99,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SMALL_CAPSULE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 75,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SMALL_CAPSULE",
                "was_picked": true
              },
              {
                "choice": "RELIC.PLANISPHERE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.QUASAR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.QUASAR"
              }
            ],
            "current_gold": 112,
            "current_hp": 72,
            "damage_taken": 3,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 123,
            "current_hp": 70,
            "damage_taken": 2,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.KNOCKOUT_BLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_CACHE"
              }
            ],
            "current_gold": 139,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 16,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COSMIC_CONCOCTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEGEMONY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONVERGENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NEUTRON_AEGIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PURITY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SALVO"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_REGENT"
              }
            ],
            "current_gold": 64,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": false
              },
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": false
              },
              {
                "choice": "RELIC.VITRUVIAN_MINION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.STARDUST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.STARDUST"
              }
            ],
            "current_gold": 75,
            "current_hp": 31,
            "damage_taken": 39,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLOCK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVERGROWTH_CRAWLERS",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE",
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 11
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MONOLOGUE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GAMMA_BLAST"
              }
            ],
            "current_gold": 90,
            "current_hp": 16,
            "damage_taken": 15,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_NORMAL",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 90,
            "current_hp": 0,
            "damage_taken": 16,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 2
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.QUASAR"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.STARDUST"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.GAMMA_BLAST"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 3,
      "potions": [
        {
          "id": "POTION.COSMIC_CONCOCTION",
          "slot_index": 1
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.SMALL_CAPSULE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PLANISPHERE"
        }
      ]
    }
  ],
  "run_time": 789,
  "schema_version": 9,
  "seed": "FCZY5RTT4Y",
  "start_time": 1778022421,
  "was_abandoned": false,
  "win": false
}