{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 7,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.TOADPOLES_WEAK",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NEW_LEAF",
                "title": {
                  "key": "NEW_LEAF.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "WINGED_BOOTS",
                "title": {
                  "key": "WINGED_BOOTS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SILKEN_TRESS",
                "title": {
                  "key": "SILKEN_TRESS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 0,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SILKEN_TRESS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 99,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "is_affected_by_fur_coat": false,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SILKEN_TRESS",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 2,
                  "id": "CARD.FRIENDSHIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.FRIENDSHIP"
              }
            ],
            "current_gold": 12,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 12,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DOORS_OF_LIGHT_AND_DARK.pages.INITIAL.options.LIGHT.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.STRIKE_NECROBINDER",
              "CARD.DEFEND_NECROBINDER"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DOORS_OF_LIGHT_AND_DARK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.FLATTEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SEVERANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FLATTEN"
              }
            ],
            "current_gold": 26,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "current_gold": 26,
            "current_hp": 0,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BODYGUARD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 2,
          "id": "CARD.FRIENDSHIP"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.FLATTEN"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.SILKEN_TRESS",
          "props": {
            "bools": [
              {
                "name": "IsUsed",
                "value": true
              }
            ]
          }
        }
      ]
    }
  ],
  "run_time": 96,
  "schema_version": 10,
  "seed": "EVJA2X83Z678",
  "start_time": 1787965553,
  "was_abandoned": true,
  "win": false
}