{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 9,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.PHROG_PARASITE_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SMALL_CAPSULE",
                "title": {
                  "key": "SMALL_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              }
            ],
            "current_gold": 99,
            "current_hp": 40,
            "damage_taken": 16,
            "event_choices": [
              {
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PRECARIOUS_SHEARS",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BACKFLIP"
              }
            ],
            "current_gold": 107,
            "current_hp": 37,
            "damage_taken": 3,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FLECHETTES"
              }
            ],
            "current_gold": 121,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.TORIC_TOUGHNESS"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_SILENT"
                }
              }
            ],
            "current_gold": 121,
            "current_hp": 37,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WOOD_CARVINGS.pages.INITIAL.options.TORUS.title",
                  "table": "events"
                },
                "variables": {
                  "BirdCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Peck"
                  },
                  "SnakeEnchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Slither"
                  },
                  "ToricCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Toric Toughness"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WOOD_CARVINGS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DAGGER_THROW"
              }
            ],
            "current_gold": 135,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLASH_OF_STEEL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REND"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FOOTWORK"
              },
              {
                "id": "CARD.DEADLY_POISON"
              }
            ],
            "current_gold": 39,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 96,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": false
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TWISTED_FUNNEL",
                "was_picked": false
              },
              {
                "choice": "RELIC.VAJRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.WING_CHARM",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 39,
            "current_hp": 58,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRACKING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 67,
            "current_hp": 24,
            "damage_taken": 34,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SWIFT_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.STRANGLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "current_gold": 79,
            "current_hp": 24,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CUBEX_CONSTRUCT_NORMAL",
            "monster_ids": [
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 115,
            "current_hp": 24,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BEATING_REMNANT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 115,
            "current_hp": 0,
            "damage_taken": 24,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE",
              "MONSTER.WRIGGLER"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.BACKFLIP"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.FLECHETTES"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.TORIC_TOUGHNESS"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.DEADLY_POISON"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.SPEED_POTION",
          "slot_index": 1
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PRECARIOUS_SHEARS"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.BEATING_REMNANT"
        }
      ]
    }
  ],
  "run_time": 438,
  "schema_version": 10,
  "seed": "C1FHGFQNYJDK",
  "start_time": 1787435698,
  "was_abandoned": false,
  "win": false
}