{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 9,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.SOUL_FYSH_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_OYSTER",
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_BONES",
                "title": {
                  "key": "NEOWS_BONES.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEOWS_FURY"
              },
              {
                "id": "CARD.WRITHE"
              }
            ],
            "current_gold": 0,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NEOWS_BONES.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 99,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NEOWS_BONES",
                "was_picked": true
              },
              {
                "choice": "RELIC.SILKEN_TRESS",
                "was_picked": true
              },
              {
                "choice": "RELIC.NEOWS_TORMENT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 2,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 8,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 8,
            "current_hp": 54,
            "damage_taken": 12,
            "event_choices": [
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.INITIAL.options.IMMERSE.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.EXIT_BATHS.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 6,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ABYSSAL_BATHS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 42,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.GREMLIN_HORN",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 42,
            "current_hp": 54,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clumsy"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.DEFEND_DEFECT",
              "CARD.COOLHEADED"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BALL_LIGHTNING"
              }
            ],
            "current_gold": 50,
            "current_hp": 53,
            "damage_taken": 1,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 50,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.ZAP"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.THUNDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.THUNDER"
              }
            ],
            "current_gold": 76,
            "current_hp": 42,
            "damage_taken": 11,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CHANDELIER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUBROUTINE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "current_gold": 90,
            "current_hp": 39,
            "damage_taken": 3,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 123,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LETTER_OPENER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.THUNDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.THUNDER"
              }
            ],
            "current_gold": 151,
            "current_hp": 11,
            "damage_taken": 28,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 151,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SMOKESTACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FTL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 164,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FOSSIL_STALKER_NORMAL",
            "monster_ids": [
              "MONSTER.FOSSIL_STALKER"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHATTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOOT_SEQUENCE"
              }
            ],
            "current_gold": 178,
            "current_hp": 26,
            "damage_taken": 9,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.HAUNTED_SHIP_NORMAL",
            "monster_ids": [
              "MONSTER.HAUNTED_SHIP"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROWESS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_GEM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLACIER"
              },
              {
                "id": "CARD.THUNDER"
              }
            ],
            "current_gold": 64,
            "current_hp": 26,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 114,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ENTROPIC_BREW",
                "was_picked": false
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": false
              },
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": false
              },
              {
                "choice": "RELIC.SCREAMING_FLAGON",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 64,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 64,
            "current_hp": 0,
            "damage_taken": 50,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.RADIANT_TINCTURE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_FYSH_BOSS",
            "monster_ids": [
              "MONSTER.SOUL_FYSH"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEOWS_FURY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.WRITHE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 2,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.CLUMSY"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.BALL_LIGHTNING"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.THUNDER"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.THUNDER"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.BOOT_SEQUENCE"
        },
        {
          "floor_added_to_deck": 15,
          "id": "CARD.GLACIER"
        },
        {
          "floor_added_to_deck": 15,
          "id": "CARD.THUNDER"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.SPEED_POTION",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NEOWS_BONES"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.SILKEN_TRESS",
          "props": {
            "bools": [
              {
                "name": "IsUsed",
                "value": true
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NEOWS_TORMENT"
        },
        {
          "floor_added_to_deck": 4,
          "id": "RELIC.GREMLIN_HORN"
        },
        {
          "floor_added_to_deck": 5,
          "id": "RELIC.WAR_PAINT"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.CHANDELIER"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.LETTER_OPENER"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.ANCHOR"
        }
      ]
    }
  ],
  "run_time": 498,
  "schema_version": 10,
  "seed": "QJ5P6GGXKKQJ",
  "start_time": 1788823523,
  "was_abandoned": false,
  "win": false
}