{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 0,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "FISHING_ROD",
                "title": {
                  "key": "FISHING_ROD.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "BOOMING_CONCH",
                "title": {
                  "key": "BOOMING_CONCH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_SACRIFICE",
                "title": {
                  "key": "NEOWS_SACRIFICE.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GUILTY",
                "props": {
                  "ints": [
                    {
                      "name": "CombatsSeen",
                      "value": 0
                    }
                  ]
                }
              }
            ],
            "current_gold": 99,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NEOWS_SACRIFICE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 75,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.AMBERGRIS",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.NEOWS_SACRIFICE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "ancient_choice": [
              {
                "TextKey": "FISHING_ROD",
                "title": {
                  "key": "FISHING_ROD.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "DOWSING_ROD",
                "title": {
                  "key": "DOWSING_ROD.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PANIC_BUTTON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREP_TIME"
              }
            ],
            "current_gold": 99,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 80,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.LEAD_PAPERWEIGHT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.LARGESSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LARGESSE"
              }
            ],
            "current_gold": 111,
            "current_hp": 73,
            "damage_taken": 2,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FIGHT_ME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHRUG_IT_OFF"
              }
            ],
            "current_gold": 112,
            "current_hp": 79,
            "damage_taken": 7,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_CACHE"
              }
            ],
            "current_gold": 129,
            "current_hp": 71,
            "damage_taken": 2,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BATTLE_TRANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              }
            ],
            "current_gold": 124,
            "current_hp": 80,
            "damage_taken": 1,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULWARK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEVASTATE"
              }
            ],
            "current_gold": 141,
            "current_hp": 66,
            "damage_taken": 5,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.UNRELENTING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.UNRELENTING"
              }
            ],
            "current_gold": 138,
            "current_hp": 79,
            "damage_taken": 7,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.I_AM_INVINCIBLE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 157,
            "current_hp": 63,
            "damage_taken": 3,
            "gold_gained": 16,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLAZE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 157,
            "current_hp": 74,
            "damage_taken": 11,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.VINE_SHAMBLER_NORMAL",
            "monster_ids": [
              "MONSTER.VINE_SHAMBLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MONOLOGUE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ASTRAL_PULSE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.GUILTY",
                "props": {
                  "ints": [
                    {
                      "name": "CombatsSeen",
                      "value": 5
                    }
                  ]
                }
              }
            ],
            "current_gold": 167,
            "current_hp": 58,
            "damage_taken": 5,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FIGHT_ME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TAUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              }
            ],
            "current_gold": 176,
            "current_hp": 73,
            "damage_taken": 7,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CUBEX_CONSTRUCT_NORMAL",
            "monster_ids": [
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.GLOW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLOW"
              }
            ],
            "current_gold": 185,
            "current_hp": 42,
            "damage_taken": 16,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.STAR_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.PACTS_END"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PACTS_END"
              }
            ],
            "current_gold": 193,
            "current_hp": 64,
            "damage_taken": 15,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INKLETS_NORMAL",
            "monster_ids": [
              "MONSTER.INKLET",
              "MONSTER.INKLET",
              "MONSTER.INKLET"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 185,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 193,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.UNRELENTING"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 230,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 244,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 51,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_INTO_SHAPE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 275,
            "current_hp": 49,
            "damage_taken": 15,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.OUTRAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.OUTRAGE"
              }
            ],
            "current_gold": 281,
            "current_hp": 49,
            "damage_taken": 21,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE",
              "MONSTER.WRIGGLER"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 275,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.DEVASTATE"
            ]
          },
          {
            "current_gold": 281,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.OUTRAGE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CLOAK_OF_STARS"
              }
            ],
            "current_gold": 285,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.EVIL_EYE"
              }
            ],
            "current_gold": 301,
            "current_hp": 54,
            "damage_taken": 1,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_NORMAL",
            "monster_ids": [
              "MONSTER.NIBBIT",
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.BRONZE_SCALES"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.LUNAR_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONSTELLATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SEEKER_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SECRET_WEAPON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MANIFEST_AUTHORITY"
              }
            ],
            "current_gold": 64,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 221,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              },
              {
                "choice": "RELIC.FROZEN_EGG",
                "was_picked": false
              },
              {
                "choice": "RELIC.SCREAMING_FLAGON",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IMPERVIOUS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DARK_SHACKLES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIMIC"
                },
                "was_picked": false
              }
            ],
            "current_gold": 142,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 159,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": true
              },
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": false
              },
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": false
              },
              {
                "choice": "RELIC.ROYAL_STAMP",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.KNOW_THY_PLACE"
              }
            ],
            "current_gold": 84,
            "current_hp": 43,
            "damage_taken": 6,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SETUP_STRIKE"
              }
            ],
            "current_gold": 153,
            "current_hp": 52,
            "damage_taken": 8,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.SNECKO_OIL",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVERGROWTH_CRAWLERS",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE",
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 84,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 153,
            "current_hp": 76,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.SEVEN_STARS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TUTOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DECISIONS_DECISIONS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SEVEN_STARS"
              }
            ],
            "current_gold": 184,
            "current_hp": 45,
            "damage_taken": 20,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.STAR_POTION"
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.PYRE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEMON_FORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OFFERING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PYRE"
              }
            ],
            "current_gold": 253,
            "current_hp": 64,
            "damage_taken": 18,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CEREMONIAL_BEAST_BOSS",
            "monster_ids": [
              "MONSTER.CEREMONIAL_BEAST"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_FLESH",
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_WING",
                "title": {
                  "key": "PAELS_WING.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_LEGION",
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 184,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 30,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_LEGION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_HORN",
                "title": {
                  "key": "PAELS_HORN.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_WING",
                "title": {
                  "key": "PAELS_WING.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_BLOOD",
                "title": {
                  "key": "PAELS_BLOOD.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 253,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_WING.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 16,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_WING",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GLIMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULWARK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.LARGESSE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.LARGESSE"
              }
            ],
            "current_gold": 203,
            "current_hp": 70,
            "damage_taken": 5,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RAMPAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPPERCUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 12,
                "id": "CARD.EVIL_EYE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 12,
                "id": "CARD.EVIL_EYE"
              }
            ],
            "current_gold": 273,
            "current_hp": 66,
            "damage_taken": 20,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 8,
                    "id": "ENCHANTMENT.VIGOROUS"
                  },
                  "floor_added_to_deck": 16,
                  "id": "CARD.SEVEN_STARS"
                },
                "enchantment": "ENCHANTMENT.VIGOROUS"
              }
            ],
            "current_gold": 203,
            "current_hp": 64,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "STONE_OF_ALL_TIME.pages.INITIAL.options.PUSH.title",
                  "table": "events"
                },
                "variables": {
                  "DrinkRandomPotion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Vulnerable Potion"
                  },
                  "DrinkMaxHpGain": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PushHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PushVigorousAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 8,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 8,
                    "id": "ENCHANTMENT.VIGOROUS"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.BASH"
                },
                "enchantment": "ENCHANTMENT.VIGOROUS"
              }
            ],
            "current_gold": 273,
            "current_hp": 60,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "STONE_OF_ALL_TIME.pages.INITIAL.options.PUSH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.STONE_OF_ALL_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 254,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 51,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.VEXING_PUZZLEBOX",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 316,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 43,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.MEAL_TICKET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.LARGESSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CHARGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STARDUST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LARGESSE"
              }
            ],
            "current_gold": 264,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FLAME_BARRIER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RUPTURE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEMON_FORM"
                },
                "was_picked": false
              }
            ],
            "current_gold": 330,
            "current_hp": 58,
            "damage_taken": 8,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 364,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.RETURN_THE_KEY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "current_gold": 430,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.RETURN_THE_KEY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LANTERN_KEY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.REFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PILLAR_OF_CREATION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REFLECT"
              }
            ],
            "current_gold": 403,
            "current_hp": 36,
            "damage_taken": 28,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CRACKER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PRIMAL_FORCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 466,
            "current_hp": 32,
            "damage_taken": 32,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 452,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 49,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.LETTER_OPENER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 516,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 50,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 10,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.PEAR",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 452,
            "current_hp": 58,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 516,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.PYRE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_CACHE"
              }
            ],
            "current_gold": 470,
            "current_hp": 56,
            "damage_taken": 2,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRUM_OF_BATTLE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 534,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER",
              "MONSTER.TOUGH_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 345,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ZEN_WEAVER.pages.INITIAL.options.EMOTIONAL_AWARENESS.title",
                  "table": "events"
                },
                "variables": {
                  "BreathingTechniquesCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 50,
                    "bool_value": false,
                    "string_value": null
                  },
                  "EmotionalAwarenessCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 125,
                    "bool_value": false,
                    "string_value": null
                  },
                  "ArachnidAcupunctureCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 250,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 7,
                "id": "CARD.PACTS_END"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              }
            ],
            "current_gold": 284,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ZEN_WEAVER.pages.INITIAL.options.ARACHNID_ACUPUNCTURE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 250,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ZEN_WEAVER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 345,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Common"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_discarded": [
              "POTION.VULNERABLE_POTION"
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.VICIOUS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              }
            ],
            "current_gold": 284,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Uncommon"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_discarded": [
              "POTION.FYSH_OIL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_FUTURE_OF_POTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.JACKPOT"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULWARK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.AUTOMATION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MANIFEST_AUTHORITY"
              },
              {
                "id": "CARD.SPECTRUM_SHIFT"
              },
              {
                "id": "CARD.JACKPOT"
              }
            ],
            "current_gold": 63,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 282,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": false
              },
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MINIATURE_CANNON",
                "was_picked": false
              },
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": false
              },
              {
                "choice": "RELIC.BREAD",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HUDDLE_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_DOWN"
                },
                "was_picked": false
              }
            ],
            "current_gold": 62,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 222,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              },
              {
                "choice": "POTION.SHIP_IN_A_BOTTLE",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CANDELABRA",
                "was_picked": true
              },
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": false
              },
              {
                "choice": "RELIC.CANDELABRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.DRAGON_FRUIT",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 63,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.SPECTRUM_SHIFT"
            ]
          },
          {
            "current_gold": 62,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.SHRUG_IT_OFF"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HEIRLOOM_HAMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEAVENLY_DRILL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOMBARDMENT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 163,
            "current_hp": 10,
            "damage_taken": 83,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 37,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.AMBERGRIS"
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.MANGLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DOMINATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PACTS_END"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MANGLE"
              }
            ],
            "current_gold": 162,
            "current_hp": 7,
            "damage_taken": 63,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FLEX_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 11
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "BEAUTIFUL_BRACELET",
                "title": {
                  "key": "BEAUTIFUL_BRACELET.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "JEWELRY_BOX",
                "title": {
                  "key": "JEWELRY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LOOMING_FRUIT",
                "title": {
                  "key": "LOOMING_FRUIT.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 163,
            "current_hp": 106,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 96,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 31,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.LOOMING_FRUIT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "ancient_choice": [
              {
                "TextKey": "BLESSED_ANTLER",
                "title": {
                  "key": "BLESSED_ANTLER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "DIAMOND_DIADEM",
                "title": {
                  "key": "DIAMOND_DIADEM.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "DELICATE_FROND",
                "title": {
                  "key": "DELICATE_FROND.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 162,
            "current_hp": 90,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BLESSED_ANTLER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 83,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.BLESSED_ANTLER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NONUPEIPE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 33,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.COSMIC_INDIFFERENCE"
              }
            ],
            "current_gold": 177,
            "current_hp": 92,
            "damage_taken": 14,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TAUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 181,
            "current_hp": 90,
            "damage_taken": 0,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.DOUBT"
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.RESONANCE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                }
              },
              {
                "final_card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.GLIMMER"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                }
              }
            ],
            "current_gold": 177,
            "current_hp": 92,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRIAL.pages.INITIAL.options.ACCEPT.title",
                  "table": "events"
                },
                "variables": {
                  "EntrantNumber": {
                    "type": "BaseDynamic",
                    "decimal_value": 680,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TRIAL.pages.NONDESCRIPT.options.INNOCENT.title",
                  "table": "events"
                },
                "variables": {
                  "EntrantNumber": {
                    "type": "BaseDynamic",
                    "decimal_value": 680,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "current_gold": 181,
            "current_hp": 90,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRIAL.pages.INITIAL.options.REJECT.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TRIAL.pages.REJECT.options.ACCEPT.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TRIAL.pages.NOBLE.options.GUILTY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TRIAL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STARDUST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 191,
            "current_hp": 89,
            "damage_taken": 3,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.ENERGY_POTION"
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPECT_A_FIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 198,
            "current_hp": 60,
            "damage_taken": 36,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              }
            ],
            "current_gold": 203,
            "current_hp": 67,
            "damage_taken": 22,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FIGHT_ME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 217,
            "current_hp": 41,
            "damage_taken": 27,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.BLOOD_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.AXEBOTS_NORMAL",
            "monster_ids": [
              "MONSTER.AXEBOT"
            ],
            "room_type": "monster",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 203,
            "current_hp": 67,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_1.title",
                  "table": "events"
                },
                "variables": {
                  "Setting1Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 180.0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting2Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 360.0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting3Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 720.0,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 217,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_1.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BATTLEWORN_DUMMY",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.BATTLEWORN_DUMMY_EVENT_V1_ENCOUNTER",
            "monster_ids": [
              "MONSTER.BATTLE_FRIEND_V1"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 251,
            "current_hp": 67,
            "damage_taken": 0,
            "gold_gained": 48,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.PARRYING_SHIELD",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 265,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 48,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "relic_choices": [
              {
                "choice": "RELIC.TUNGSTEN_ROD",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CONVERGENCE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 267,
            "current_hp": 54,
            "damage_taken": 13,
            "gold_gained": 16,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HELLRAISER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPECT_A_FIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 280,
            "current_hp": 52,
            "damage_taken": 5,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GLOBE_HEAD_NORMAL",
            "monster_ids": [
              "MONSTER.GLOBE_HEAD"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 267,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 31,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 280,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.MANGLE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 41,
                  "id": "CARD.PATTER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.QUASAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PATTER"
              }
            ],
            "current_gold": 310,
            "current_hp": 60,
            "damage_taken": 25,
            "gold_gained": 43,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "relic_choices": [
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.INFLAME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 321,
            "current_hp": 32,
            "damage_taken": 28,
            "gold_gained": 41,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CHARONS_ASHES",
                "was_picked": true
              },
              {
                "choice": "RELIC.TINY_MAILBOX",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRASH_LANDING"
                },
                "was_picked": false
              }
            ],
            "current_gold": 321,
            "current_hp": 35,
            "damage_taken": 25,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.TREMBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TREMBLE"
              }
            ],
            "current_gold": 321,
            "current_hp": 13,
            "damage_taken": 27,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_LOST_AND_FORGOTTEN_NORMAL",
            "monster_ids": [
              "MONSTER.THE_LOST",
              "MONSTER.THE_FORGOTTEN"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_potions": [
              "POTION.FAIRY_IN_A_BOTTLE"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLIMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SALVO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PILLAR_OF_CREATION"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 34,
                "id": "CARD.DOUBT"
              }
            ],
            "current_gold": 76,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 245,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_choices": [
              {
                "choice": "POTION.FAIRY_IN_A_BOTTLE",
                "was_picked": true
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              },
              {
                "choice": "POTION.ENTROPIC_BREW",
                "was_picked": false
              }
            ],
            "potion_discarded": [
              "POTION.STRENGTH_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KUNAI",
                "was_picked": false
              },
              {
                "choice": "RELIC.LANTERN",
                "was_picked": false
              },
              {
                "choice": "RELIC.RINGING_TRIANGLE",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOWL_FROM_BEYOND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FORGOTTEN_RITUAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRUELTY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THRUMMING_HATCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIMIC"
                },
                "was_picked": false
              }
            ],
            "current_gold": 91,
            "current_hp": 28,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 230,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOOD_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": true
              },
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": false
              },
              {
                "choice": "RELIC.DEMON_TONGUE",
                "was_picked": false
              },
              {
                "choice": "RELIC.TOOLBOX",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 76,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 31,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 91,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              }
            ],
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 76,
            "current_hp": 10,
            "damage_taken": 56,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198854416655,
            "potion_used": [
              "POTION.POWER_POTION"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 91,
            "current_hp": 7,
            "damage_taken": 75,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "is_affected_by_fur_coat": false,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198419322369,
            "potion_used": [
              "POTION.BLOOD_POTION",
              "POTION.WEAK_POTION",
              "POTION.RADIANT_TINCTURE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.QUEEN_BOSS",
            "monster_ids": [
              "MONSTER.TORCH_HEAD_AMALGAM",
              "MONSTER.QUEEN"
            ],
            "room_type": "boss",
            "turns_taken": 14
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "DAMAGE_LEADER",
          "rarity": "bronze"
        },
        {
          "id": "DEBUFFER",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "bronze"
        },
        {
          "id": "GLUTTON",
          "rarity": "silver"
        }
      ],
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.DEVASTATE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.ASTRAL_PULSE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.GLOW"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.CLOAK_OF_STARS"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.MANIFEST_AUTHORITY"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.KNOW_THY_PLACE"
        },
        {
          "enchantment": {
            "amount": 8,
            "id": "ENCHANTMENT.VIGOROUS"
          },
          "floor_added_to_deck": 16,
          "id": "CARD.SEVEN_STARS"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.LARGESSE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.LARGESSE"
        },
        {
          "floor_added_to_deck": 23,
          "id": "CARD.REFLECT"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "floor_added_to_deck": 29,
          "id": "CARD.MANIFEST_AUTHORITY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.SPECTRUM_SHIFT"
        },
        {
          "floor_added_to_deck": 29,
          "id": "CARD.JACKPOT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.COSMIC_INDIFFERENCE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.RESONANCE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.GLIMMER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 41,
          "id": "CARD.PATTER"
        },
        {
          "floor_added_to_deck": 43,
          "id": "CARD.PILLAR_OF_CREATION"
        }
      ],
      "id": 76561198854416655,
      "max_potion_slot_count": 3,
      "potions": [
        {
          "id": "POTION.FAIRY_IN_A_BOTTLE",
          "slot_index": 1
        },
        {
          "id": "POTION.ENERGY_POTION",
          "slot_index": 2
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NEOWS_SACRIFICE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.JUZU_BRACELET"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.RIPPLE_BASIN"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_LEGION",
          "props": {
            "strings": [
              {
                "name": "Skin",
                "value": "horns"
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.VEXING_PUZZLEBOX"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.STONE_CRACKER"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.LETTER_OPENER"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.LOOMING_FRUIT"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.PARRYING_SHIELD"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.REPTILE_TRINKET"
        }
      ]
    },
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "bronze"
        },
        {
          "id": "HIGHLANDER",
          "rarity": "bronze"
        },
        {
          "id": "TINY_DECK",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "enchantment": {
            "amount": 8,
            "id": "ENCHANTMENT.VIGOROUS"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PREP_TIME"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.UNRELENTING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 10,
          "id": "CARD.OUTRAGE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.SETUP_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.PYRE"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.EVIL_EYE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.MANGLE"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.TREMBLE"
        }
      ],
      "id": 76561198419322369,
      "max_potion_slot_count": 3,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LEAD_PAPERWEIGHT"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.PERMAFROST"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.STRIKE_DUMMY"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.FESTIVE_POPPER"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_WING",
          "props": {
            "ints": [
              {
                "name": "RewardsSacrificed",
                "value": 10
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.MEAL_TICKET"
        },
        {
          "floor_added_to_deck": 21,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.PEAR"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.CANDELABRA"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.BLESSED_ANTLER"
        },
        {
          "floor_added_to_deck": 33,
          "id": "RELIC.BLOOD_VIAL"
        },
        {
          "floor_added_to_deck": 36,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.TUNGSTEN_ROD"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.CHARONS_ASHES"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.TINY_MAILBOX"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.ORNAMENTAL_FAN"
        }
      ]
    }
  ],
  "run_time": 3343,
  "schema_version": 10,
  "seed": "LUASL2C9RZH8",
  "start_time": 1788048345,
  "was_abandoned": false,
  "win": true
}