{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 9,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.CEREMONIAL_BEAST_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PRECISE_SCISSORS",
                "title": {
                  "key": "PRECISE_SCISSORS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_SACRIFICE",
                "title": {
                  "key": "NEOWS_SACRIFICE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PRODUCTION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.JACK_OF_ALL_TRADES"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LEAD_PAPERWEIGHT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CLOAK_AND_DAGGER"
              }
            ],
            "current_gold": 111,
            "current_hp": 47,
            "damage_taken": 9,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 111,
            "current_hp": 47,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "UNREST_SITE.pages.INITIAL.options.KILL.title",
                  "table": "events"
                },
                "variables": {
                  "MaxHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 8,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 8,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ICE_CREAM",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.UNREST_SITE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEADING_STRIKE"
              }
            ],
            "current_gold": 120,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLUR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DAGGER_SPRAY"
              }
            ],
            "current_gold": 129,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLUR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 139,
            "current_hp": 38,
            "damage_taken": 9,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.STRENGTH_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_NORMAL",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DODGE_AND_ROLL"
              }
            ],
            "current_gold": 152,
            "current_hp": 29,
            "damage_taken": 9,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVERGROWTH_CRAWLERS",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE",
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 152,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STRATAGEM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_DOWN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FOOTWORK"
              }
            ],
            "current_gold": 79,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 73,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              },
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": false
              },
              {
                "choice": "POTION.DROPLET_OF_PRECOGNITION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LASTING_CANDY",
                "was_picked": false
              },
              {
                "choice": "RELIC.ORICHALCUM",
                "was_picked": false
              },
              {
                "choice": "RELIC.TOOLBOX",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 118,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.INTIMIDATING_HELMET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SUCKER_PUNCH"
              }
            ],
            "current_gold": 145,
            "current_hp": 29,
            "damage_taken": 18,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE",
              "MONSTER.WRIGGLER"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 12,
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PINPOINT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.FLECHETTES"
              }
            ],
            "current_gold": 145,
            "current_hp": 29,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Uncommon"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_discarded": [
              "POTION.RADIANT_TINCTURE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_FUTURE_OF_POTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 145,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOUNCING_FLASK"
                },
                "was_picked": false
              }
            ],
            "current_gold": 154,
            "current_hp": 42,
            "damage_taken": 5,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.RUBY_RAIDERS_NORMAL",
            "monster_ids": [
              "MONSTER.BRUTE_RUBY_RAIDER",
              "MONSTER.AXE_RUBY_RAIDER",
              "MONSTER.TRACKER_RUBY_RAIDER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.THE_HUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHANTOM_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PURITY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_OF_GREED"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 54,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.CLARITY",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PEN_NIB",
                "was_picked": false
              },
              {
                "choice": "RELIC.TINGSHA",
                "was_picked": false
              },
              {
                "choice": "RELIC.MEMBERSHIP_CARD",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 54,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.JACK_OF_ALL_TRADES"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 54,
            "current_hp": 0,
            "damage_taken": 42,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.WEAK_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CEREMONIAL_BEAST_BOSS",
            "monster_ids": [
              "MONSTER.CEREMONIAL_BEAST"
            ],
            "room_type": "boss",
            "turns_taken": 12
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.JACK_OF_ALL_TRADES"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.CLOAK_AND_DAGGER"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.DAGGER_SPRAY"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.DODGE_AND_ROLL"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.SUCKER_PUNCH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 12,
          "id": "CARD.FLECHETTES"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LEAD_PAPERWEIGHT"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.ICE_CREAM"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.INTIMIDATING_HELMET"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.ANCHOR"
        }
      ]
    }
  ],
  "run_time": 874,
  "schema_version": 10,
  "seed": "KKF9EBVK8CWF",
  "start_time": 1788557423,
  "was_abandoned": false,
  "win": false
}