{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 9,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.DECIMILLIPEDE_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "WINGED_BOOTS",
                "title": {
                  "key": "WINGED_BOOTS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_TALISMAN",
                "title": {
                  "key": "NEOWS_TALISMAN.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SILVER_CRUCIBLE",
                "title": {
                  "key": "SILVER_CRUCIBLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NEOWS_TALISMAN.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NEOWS_TALISMAN",
                "was_picked": true
              }
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.STRIKE_REGENT",
              "CARD.DEFEND_REGENT"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PARRY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REFINE_BLADE"
              }
            ],
            "current_gold": 106,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.CURE_ALL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SPOILS_OF_BATTLE"
              }
            ],
            "current_gold": 113,
            "current_hp": 57,
            "damage_taken": 3,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.HEAVENLY_DRILL"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                }
              },
              {
                "final_card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_REGENT"
                }
              }
            ],
            "current_gold": 0,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MORPHIC_GROVE.pages.INITIAL.options.GROUP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 113,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 113
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.MORPHIC_GROVE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.BULWARK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BULWARK"
              }
            ],
            "current_gold": 15,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 5,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.BLOCK_POTION"
            ],
            "potion_used": [
              "POTION.FRUIT_JUICE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 15,
            "current_hp": 62,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "AROMA_OF_CHAOS.pages.INITIAL.options.MAINTAIN_CONTROL.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.BULWARK"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.AROMA_OF_CHAOS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 48,
            "current_hp": 41,
            "damage_taken": 21,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FROZEN_EGG",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 48,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.REFINE_BLADE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 9,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONVERGENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 56,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MAWLER_NORMAL",
            "monster_ids": [
              "MONSTER.MAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 87,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.KINGLY_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.KNOW_THY_PLACE"
              }
            ],
            "current_gold": 96,
            "current_hp": 34,
            "damage_taken": 7,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FLYCONID_NORMAL",
            "monster_ids": [
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.FLYCONID"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.THE_SMITH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PARTICLE_WALL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.THE_SMITH"
              }
            ],
            "current_gold": 129,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.CURE_ALL"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORANGE_DOUGH",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 129,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.KNOW_THY_PLACE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.LUNAR_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLIMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PANIC_BUTTON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BEGONE"
              }
            ],
            "current_gold": 104,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 25,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STAR_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": false
              },
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHEMICAL_X",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 136,
            "current_hp": 33,
            "damage_taken": 16,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.REGEN_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE",
              "MONSTER.WRIGGLER"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 136,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 17,
                  "id": "CARD.SWORD_SAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DECISIONS_DECISIONS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.NEUTRON_AEGIS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SWORD_SAGE"
              }
            ],
            "current_gold": 211,
            "current_hp": 26,
            "damage_taken": 31,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK",
              "POTION.RADIANT_TINCTURE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CEREMONIAL_BEAST_BOSS",
            "monster_ids": [
              "MONSTER.CEREMONIAL_BEAST"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOASTY_MITTENS",
                "title": {
                  "key": "TOASTY_MITTENS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              }
            ],
            "current_gold": 211,
            "current_hp": 69,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 43,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NUTRITIOUS_SOUP",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MANIFEST_AUTHORITY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 225,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_NECTAR"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.ENLIGHTENMENT"
              },
              {
                "id": "CARD.ENLIGHTENMENT"
              }
            ],
            "current_gold": 175,
            "current_hp": 69,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ZEN_WEAVER.pages.INITIAL.options.BREATHING_TECHNIQUES.title",
                  "table": "events"
                },
                "variables": {
                  "BreathingTechniquesCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 50,
                    "bool_value": false,
                    "string_value": null
                  },
                  "EmotionalAwarenessCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 125,
                    "bool_value": false,
                    "string_value": null
                  },
                  "ArachnidAcupunctureCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 250,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 50,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ZEN_WEAVER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROPHESIZE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SPOILS_OF_BATTLE"
              }
            ],
            "current_gold": 183,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LUNAR_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLIMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IMPATIENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REND"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.FURNACE"
              }
            ],
            "current_gold": 105,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 78,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": false
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PANTOGRAPH",
                "was_picked": false
              },
              {
                "choice": "RELIC.MEAT_ON_THE_BONE",
                "was_picked": false
              },
              {
                "choice": "RELIC.THE_ABACUS",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 205,
            "current_hp": 69,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.RETURN_THE_KEY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LANTERN_KEY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 205,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.ENLIGHTENMENT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROPHESIZE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 213,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK",
              "POTION.POTION_SHAPED_ROCK"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUMBERING_BEETLE_NORMAL",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_SILK",
              "MONSTER.SLUMBERING_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 251,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 251,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.ENLIGHTENMENT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 5,
                  "id": "CARD.BULWARK"
                },
                "enchantment": "ENCHANTMENT.NIMBLE"
              }
            ],
            "current_gold": 251,
            "current_hp": 69,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_PASSAGE.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sharp"
                  },
                  "Enchantment2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Nimble"
                  },
                  "Enchantment3": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Swift"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SELF_HELP_BOOK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 251,
            "current_hp": 0,
            "damage_taken": 69,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.REFINE_BLADE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.SPOILS_OF_BATTLE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.HEAVENLY_DRILL"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.CLOAK_OF_STARS"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 5,
          "id": "CARD.BULWARK"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.KNOW_THY_PLACE"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.THE_SMITH"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.BEGONE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.SWORD_SAGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.ENLIGHTENMENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.ENLIGHTENMENT"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.SPOILS_OF_BATTLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.FURNACE"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NEOWS_TALISMAN"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.FROZEN_EGG"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.FESTIVE_POPPER"
        },
        {
          "floor_added_to_deck": 12,
          "id": "RELIC.ORANGE_DOUGH"
        },
        {
          "floor_added_to_deck": 15,
          "id": "RELIC.PETRIFIED_TOAD"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.NUTRITIOUS_SOUP"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        }
      ]
    }
  ],
  "run_time": 1380,
  "schema_version": 10,
  "seed": "38MWPMJA63WA",
  "start_time": 1789868911,
  "was_abandoned": false,
  "win": false
}