{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 9,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NUTRITIOUS_OYSTER",
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SILVER_CRUCIBLE",
                "title": {
                  "key": "SILVER_CRUCIBLE.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SILVER_CRUCIBLE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SILVER_CRUCIBLE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 2,
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CLOAK_AND_DAGGER"
              }
            ],
            "current_gold": 109,
            "current_hp": 53,
            "damage_taken": 3,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 3,
                  "id": "CARD.RICOCHET"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.RICOCHET"
              }
            ],
            "current_gold": 122,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 122,
            "current_hp": 50,
            "damage_taken": 7,
            "event_choices": [
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.INITIAL.options.IMMERSE.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.EXIT_BATHS.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 4,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 4,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ABYSSAL_BATHS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 2,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CLAM_ROLL.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Spicy Snappy"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.SUSPICIOUS_CONDIMENT.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Spicy Snappy"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CLAM_ROLL.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Spicy Snappy"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.GRAB_SOMETHING_OFF_THE_BELT.options.LEAVE.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Spicy Snappy"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 120,
            "gold_stolen": 0,
            "hp_healed": 20,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FAIRY_IN_A_BOTTLE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ENDLESS_CONVEYOR",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 6,
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.REFLEX"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CALCULATED_GAMBLE"
              }
            ],
            "current_gold": 11,
            "current_hp": 63,
            "damage_taken": 7,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.MASTER_PLANNER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PINPOINT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MASTER_PLANNER"
              }
            ],
            "current_gold": 41,
            "current_hp": 20,
            "damage_taken": 43,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOWLER_HAT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 11
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 41,
            "current_hp": 20,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.MASTER_PLANNER"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 41,
            "current_hp": 0,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 1
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.CLOAK_AND_DAGGER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.RICOCHET"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 6,
          "id": "CARD.CALCULATED_GAMBLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 7,
          "id": "CARD.MASTER_PLANNER"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.FAIRY_IN_A_BOTTLE",
          "slot_index": 0
        },
        {
          "id": "POTION.BLOCK_POTION",
          "slot_index": 1
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.SILVER_CRUCIBLE",
          "props": {
            "ints": [
              {
                "name": "TimesUsed",
                "value": 3
              },
              {
                "name": "TreasureRoomsEntered",
                "value": 0
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.BOWLER_HAT"
        }
      ]
    }
  ],
  "run_time": 354,
  "schema_version": 10,
  "seed": "FTT8S1SZCVXT",
  "start_time": 1789690616,
  "was_abandoned": true,
  "win": false
}