{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 9,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.TERROR_EEL_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "GOLDEN_PEARL",
                "title": {
                  "key": "GOLDEN_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "HEFTY_TABLET",
                "title": {
                  "key": "HEFTY_TABLET.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SERPENT_FORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MASTER_PLANNER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ABRASIVE"
              },
              {
                "id": "CARD.INJURY"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "HEFTY_TABLET.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.HEFTY_TABLET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEADING_STRIKE"
              }
            ],
            "current_gold": 111,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ACCELERANT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 120,
            "current_hp": 54,
            "damage_taken": 2,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCELERANT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THRUMMING_HATCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEADING_STRIKE"
              }
            ],
            "current_gold": 68,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 52,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.CUNNING_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": false
              },
              {
                "choice": "RELIC.GAMBLING_CHIP",
                "was_picked": false
              },
              {
                "choice": "RELIC.BELT_BUCKLE",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 82,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.SHOCKWAVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RESTLESSNESS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PURITY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHOCKWAVE"
              }
            ],
            "current_gold": 82,
            "current_hp": 49,
            "damage_taken": 5,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.RIP.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BRAIN_LEECH",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 82,
            "current_hp": 0,
            "damage_taken": 49,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ABRASIVE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.INJURY"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.SHOCKWAVE"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.HEFTY_TABLET"
        }
      ]
    }
  ],
  "run_time": 397,
  "schema_version": 10,
  "seed": "Y576HSVWH3DC",
  "start_time": 1790727347,
  "was_abandoned": false,
  "win": false
}