{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 9,
  "build_id": "v0.111.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.CORPSE_SLUGS_NORMAL",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_OYSTER",
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "KALEIDOSCOPE",
                "title": {
                  "key": "KALEIDOSCOPE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SILKEN_TRESS",
                "title": {
                  "key": "SILKEN_TRESS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 0,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SILKEN_TRESS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 99,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SILKEN_TRESS",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "floor_added_to_deck": 2,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.EXPOSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GLAM"
                  },
                  "id": "CARD.REFLEX"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "enchantment": {
                  "amount": 1,
                  "id": "ENCHANTMENT.GLAM"
                },
                "id": "CARD.BACKFLIP"
              }
            ],
            "current_gold": 15,
            "current_hp": 53,
            "damage_taken": 3,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 15,
            "current_hp": 63,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.INITIAL.options.ABSTAIN.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ABYSSAL_BATHS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.NIMBLE"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.SURVIVOR"
                },
                "enchantment": "ENCHANTMENT.NIMBLE"
              }
            ],
            "current_gold": 15,
            "current_hp": 63,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_PASSAGE.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sharp"
                  },
                  "Enchantment2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Nimble"
                  },
                  "Enchantment3": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Swift"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SELF_HELP_BOOK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 25,
            "current_hp": 61,
            "damage_taken": 2,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.MAZALETHS_GIFT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 33,
            "current_hp": 57,
            "damage_taken": 4,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 33,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.BACKFLIP"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "current_gold": 33,
            "current_hp": 0,
            "damage_taken": 21,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "is_affected_by_fur_coat": false,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_NORMAL",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.NIMBLE"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.GLAM"
          },
          "floor_added_to_deck": 2,
          "id": "CARD.BACKFLIP"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.ACROBATICS"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.MAZALETHS_GIFT",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.SILKEN_TRESS",
          "props": {
            "bools": [
              {
                "name": "IsUsed",
                "value": true
              }
            ]
          }
        }
      ]
    }
  ],
  "run_time": 294,
  "schema_version": 10,
  "seed": "S60UWFX7ZYJG",
  "start_time": 1791053462,
  "was_abandoned": true,
  "win": false
}